### ISSUE TITLE
Suggestion: Include JRE links on DL page

### ISSUE THREAD

**Issue by ret394** [zaproxy/zaproxy-website#124]
**Is your feature request related to a problem? Please describe.**
curious why you don't provide a JRE on releases page since Java is required. Unlike other projects that do so, this project seems a bit eager to not ignore good docs. Thanks to the teamwork.

**Describe the solution you'd like**
It's trivial and I'm out of time. ping me if you can't figure it out.

**Describe alternatives you've considered**
lots of them, but none are simple, repeatable and pragmatic enough.

**Would you like to help implementing this feature?**
No, sorry.

you're welcome, as always. all the best. 👍

<sub>Edit: By @kingthorin removed unnecessary and spurious text</sub>

**Comment by kingthorin** [comment]
For my 2 cents: 
Mainly because it's up to the user's discretion. Since so many people use OpenJDK now which flavor(s) do we suggest? What happens if/when we miss an alternative? Seems like a maintenance headache with nearly zero gain.

The Download page does clearly articulate that a JRE is required.
